name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test against Rails main
        if: ${{ matrix.ruby == 2.7 }}
        run: |
          bundle exec appraisal rails-main bundle install
          bundle exec appraisal rails-main rake test

      - name: Test against Rails 7.1
        run: |
          bundle exec appraisal rails-7-1 bundle install
          bundle exec appraisal rails-7-1 rake test

      - name: Test against Rails 6.0
        run: |
          bundle exec appraisal rails-6-0 bundle install
          bundle exec appraisal rails-6-0 rake test

      - name: Test against Rails 5.2
        run: |
          bundle exec appraisal rails-5-2 bundle install
          bundle exec appraisal rails-5-2 rake test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.3]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake lint
